# The URL the site will be built for
base_url = "https://blog.cameron.rs"

title="cameron - software engineer"

description = "This is my blog where I sometimes write about my random thoughts"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false


taxonomies = [
    { name = "tags" },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"
render_emoji = true

[extra]
image_api="https://og.cameron.rs/api/"
github="https://github.com/wzid"
linkedin="https://www.linkedin.com/in/cameron-k-a00565257"
email="me@cameron.rs"
# Put all your custom variables here
anpu_date_format="%B %e %Y"
menu_links = [
    { url = "$BASE_URL/", name = "Blog" },
    { url = "https://projects.cameron.rs", name = "Projects" },
    { url = "https://docs.cameron.rs", name = "Documentation" },
]